languages:
  #  sw: { name: Swahili, ivr_key: "1", whisper_code: sw, twilio_say_voice: null, sms_prefix: SW, script: latin }
  hi: { name: Hindi,   ivr_key: "3", whisper_code: hi, twilio_say_voice: "Polly.Aditi", sms_prefix: HI, script: devanagari }

default_language: hi
